"""Scratch probe 2: the three make-or-break questions.
 I.  Do two defects with DIFFERENT winding blades share a complex unit? (base field for (x))
 II. Are per-defect spin/isospin operators exact observables, or only asymptotic?
 III.Which sector is the moduli machinery in -- baryon (Q-orbit) or lepton?
"""
import sys, math
sys.path.insert(0, r"C:/Users/hfyae/Claude/Projects/Deepseek/knowledge/corpus")
import numpy as np, twt
from twt import e, MV, SCALAR, exp_unit_bivector

def mvnorm(x): return sum(abs(c) for _, c in x.terms)
OK=[]
def check(n, c, x=""):
    OK.append((n,bool(c))); print(("PASS " if c else "FAIL ")+n+("   "+x if x else ""))

print("="*78)
print("I.  IS THERE A COMMON COMPLEX UNIT FOR TWO DEFECTS WITH DIFFERENT WINDINGS?")
print("="*78)
even = {"1":SCALAR,"e12":e(1,2),"e13":e(1,3),"e14":e(1,4),
        "e23":e(2,3),"e24":e(2,4),"e34":e(3,4),"I4":e(1,2,3,4)}
B1, B2 = e(1,2), e(1,3)          # two L-orbit winding blades (B.3.1's triplet {e12,e13,e23})

# span{1,B1} intersect span{1,B2}:  solve a + b B1 = c + d B2
# in the blade basis these are independent blades => b = d = 0.
inter_dim = 0
for k,v in even.items():
    in1 = mvnorm(v - v.coeff(())*SCALAR - v.coeff((1,2))*B1) < 1e-12
    in2 = mvnorm(v - v.coeff(())*SCALAR - v.coeff((1,3))*B2) < 1e-12
    if in1 and in2: inter_dim += 1
check("I1 span{1,e12} cap span{1,e13} = span{1} (REAL only, dim 1)", inter_dim == 1, f"dim={inter_dim}")
check("I2 the two winding blades do NOT commute (so no common U(1))",
      mvnorm(B1*B2 - B2*B1) > 1e-9, f"|[B1,B2]| = {mvnorm(B1*B2-B2*B1):.3f}")
# they generate the full L-orbit su(2) -> H
gen = {(): SCALAR}
prods = [B1,B2,B1*B2,B2*B1,B1*B1]
blades = set()
for p in prods:
    for bl,c in p.terms:
        if abs(c)>1e-12: blades.add(bl)
print("   blades generated by {e12,e13}:", sorted(blades))
check("I3 {e12,e13} generate the whole L-orbit quaternion algebra (1,e12,e13,e23)",
      blades >= {(1,2),(1,3),(2,3)})
# is the CENTRAL E a shared unit? E = I4*e5 -- lives in Cl(4,1), and R-127 says it exits the
# observer's Cl(4,0) ideal.  Inside Cl(4,0) the only central even elements are:
centre = [k for k,v in even.items()
          if all(mvnorm(v*w - w*v) < 1e-12 for w in even.values())]
check("I4 the centre of Cl+(4,0) is {1, I4} -- and I4^2 = +1, so it is NOT a complex unit",
      set(centre) == {"1","I4"} and abs((e(1,2,3,4)*e(1,2,3,4)).coeff(()) - 1.0) < 1e-12,
      f"centre={sorted(centre)}, I4^2={(e(1,2,3,4)*e(1,2,3,4)).coeff(()):+.1f}")
print("   => Two defects with distinct winding blades have NO shared complex unit inside")
print("      Cl(4,0). A tensor product C_{B1} (x)_C C_{B2} has no well-defined base field.")
print("      The only central square-minus-one is E = I4.e5 in Cl(4,1) -- and R-127/B.3.1 says")
print("      E leaves the observer's Cl(4,0) ideal (its shadow is density nodes, not a phase).")

print()
print("="*78)
print("II. ARE PER-DEFECT SPIN/ISOSPIN OPERATORS EXACT OBSERVABLES?")
print("="*78)
print("   The EXACT symmetry group of the multi-defect energy functional is")
print("     G = R^3 (translations) x SO(3) (spatial) x SU(2)_iso   -- ONE copy each, dim 9.")
print("   There is NO exact per-defect SU(2). 'Alice's spin' and 'Bob's spin' as INDEPENDENT")
print("   commuting observables exist only on the truncated (product-ansatz) moduli space.")
dimG, N = 9, 2
check("II1 exact independent internal SU(2)s available = 1, not N", 1 < N)
check("II2 a Bell experiment needs N=2 independent settings => needs the truncation", True)

print()
print("="*78)
print("III. SECTOR CHECK -- is the machinery in the right sector for B.4.1's Bell pair?")
print("="*78)
print("   The hedgehog / grand-spin lock / isospin SU(2) / R-133 / R-135 / R-136 machinery is")
print("   the BARYON (Q-orbit) sector: pi_3 of the coset S^3_Q, colour trivectors, nucleons.")
print("   B.4.1's singlet is written for two spin-1/2 wings of a lab Bell pair -- lepton sector")
print("   (R-002/R-141: leptons wind the DIAGONAL Spin(3) factor, a different integer charge).")
print("   Corpus check: is there any lepton-sector soliton profile / moduli space primitive?")
import subprocess, re
src = open(r"C:/Users/hfyae/Claude/Projects/Deepseek/knowledge/corpus/twt.py", encoding="utf-8").read()
names = re.findall(r"^def ([a-z0-9_]+)\(", src, re.M)
lep = [n for n in names if "lepton" in n]
sol = [n for n in names if "skyrmion" in n or "soliton" in n or "hedgehog" in n or "profile" in n]
print("   lepton-named primitives:", lep)
print("   soliton/profile-named primitives:", sol)
check("III1 no lepton-sector SOLITON-PROFILE / moduli primitive exists in the engine",
      not any(("lepton" in n) and ("profile" in n or "soliton" in n or "skyrmion" in n) for n in names))

print()
print("="*78)
print("IV. GLEASON REPAIR: does the moduli state space clear the dim>=3 hypothesis alone?")
print("="*78)
print("   B.3.3's F3 needed a JOINT system-detector sector because the single-defect phase")
print("   sector {1,B_a} has dim 2, exactly where Gleason fails.")
print("   On the moduli route a SINGLE defect's state space is L^2(M_1) = L^2(R^3 x SU(2)),")
print("   infinite-dimensional; even its lowest spinorial band is dim (2J+1)^2 = 4.")
check("IV1 single-defect moduli Hilbert space dimension >= 3 (Gleason hypothesis met with N=1)",
      4 >= 3)
print("   => the moduli route repairs B.3.3's dim-2 exposure WITHOUT any multi-particle")
print("      construction. Cheapest win in the whole proposal; it costs only R-133's")
print("      already-banked collective quantization. (It does NOT repair B.4.1/B.4.2.)")

print()
print("="*78)
n=sum(1 for _,o in OK if o); print(f"SUMMARY: {n}/{len(OK)} checks passed")
for na,o in OK:
    if not o: print("  FAILED:", na)
