"""Scratch probe: moduli-space route to a multi-defect state space.
NOT banked. Every result below is verified here in-session; nothing is written to twt.py.
Run:  PYTHONUTF8=1 python moduli_probe.py
"""
import sys, math, itertools
sys.path.insert(0, r"C:/Users/hfyae/Claude/Projects/Deepseek/knowledge/corpus")
import numpy as np
import twt
from twt import e, MV, SCALAR, I4, exp_unit_bivector

OK = []
def check(name, cond, extra=""):
    OK.append((name, bool(cond)))
    print(("PASS " if cond else "FAIL ") + name + ("   " + extra if extra else ""))

print("="*78)
print("A.  CHARGE SPLIT of the 8 even blades under the U(1) generated by B_a = e12")
print("="*78)

even = {"1": SCALAR, "e12": e(1,2), "e13": e(1,3), "e14": e(1,4),
        "e23": e(2,3), "e24": e(2,4), "e34": e(3,4), "I4": e(1,2,3,4)}
B = e(1,2)

def mvnorm(x):
    return sum(abs(c) for _, c in x.terms)

# (A1) commutant
comm = [k for k,v in even.items() if mvnorm(v*B - B*v) < 1e-12]
anti = [k for k,v in even.items() if mvnorm(v*B + B*v) < 1e-12]
check("A1 commutant of e12 in Cl+(4,0) == {1,e12,e34,I4}",
      set(comm) == {"1","e12","e34","I4"}, str(sorted(comm)))
check("A1b anticommutant == {e13,e14,e23,e24}",
      set(anti) == {"e13","e14","e23","e24"}, str(sorted(anti)))

# (A2) ADJOINT (two-sided) action X -> R X ~R,  R = exp(theta B/2): charge-0 vs doublets
th = 0.7
R = exp_unit_bivector(B, th/2.0)
Rt = exp_unit_bivector(B, -th/2.0)
def ad(X): return R*X*Rt
c, s = math.cos(th), math.sin(th)
check("A2 e13 -> cos*e13 - sin*e23", mvnorm(ad(even["e13"]) - (c*even["e13"] - s*even["e23"])) < 1e-12)
check("A2 e23 -> sin*e13 + cos*e23", mvnorm(ad(even["e23"]) - (s*even["e13"] + c*even["e23"])) < 1e-12)
check("A2 e14 -> cos*e14 - sin*e24", mvnorm(ad(even["e14"]) - (c*even["e14"] - s*even["e24"])) < 1e-12)
check("A2 e24 -> sin*e14 + cos*e24", mvnorm(ad(even["e24"]) - (s*even["e14"] + c*even["e24"])) < 1e-12)
check("A2 e34 adjoint-invariant", mvnorm(ad(even["e34"]) - even["e34"]) < 1e-12)
check("A2 I4  adjoint-invariant", mvnorm(ad(even["I4"]) - even["I4"]) < 1e-12)

# (A3) the FLUCTUATION-relevant action is RIGHT multiplication psi -> psi*exp(theta B)
#      (that is the action generating the phase sector of B.3.1). Charges under it:
Rr = exp_unit_bivector(B, th)
def rmul(X): return X*Rr
# a blade X has "right charge q" if X*exp(th B) = cos(q th) X + sin(q th) (X B)
for k,v in even.items():
    out = rmul(v)
    pred = math.cos(th)*v + math.sin(th)*(v*B)
    assert mvnorm(out - pred) < 1e-12, k
print("  A3: right-multiplication acts on EVERY even blade with the same charge |q|=1;")
print("      it pairs blades {1,e12},{e13,-e23}... i.e. 4 complex lines, NOT 1 neutral + doublets.")
print("      => the 'charge split' of A1/A2 is the ADJOINT grading, a DIFFERENT action from the")
print("         right-multiplication that generates B.3.1's phase sector. Do not conflate them.")
# exhibit the 4 right-invariant complex lines
lines = []
for k,v in even.items():
    partner = v*B
    lines.append((k, [kk for kk,vv in even.items() if mvnorm(vv - partner) < 1e-12 or mvnorm(vv + partner) < 1e-12]))
print("      right-mult pairing (X, X*e12):", [(k,p) for k,p in lines])

print()
print("="*78)
print("B.  B=1 HEDGEHOG: the stabilizer, and the exact moduli dimension")
print("="*78)

sx = np.array([[0,1],[1,0]], dtype=complex)
sy = np.array([[0,-1j],[1j,0]], dtype=complex)
sz = np.array([[1,0],[0,-1]], dtype=complex)
sig = [sx, sy, sz]
Id2 = np.eye(2, dtype=complex)

def Umat(x, F):
    r = np.linalg.norm(x)
    if r < 1e-14:
        return math.cos(F(0.0))*Id2
    n = x/r
    return math.cos(F(r))*Id2 + 1j*math.sin(F(r))*(n[0]*sx + n[1]*sy + n[2]*sz)

def su2(axis, ang):
    a = np.array(axis, dtype=float); a = a/np.linalg.norm(a)
    return math.cos(ang/2)*Id2 - 1j*math.sin(ang/2)*(a[0]*sx + a[1]*sy + a[2]*sz)

def so3(axis, ang):
    a = np.array(axis, dtype=float); a = a/np.linalg.norm(a)
    K = np.array([[0,-a[2],a[1]],[a[2],0,-a[0]],[-a[1],a[0],0]])
    return np.eye(3) + math.sin(ang)*K + (1-math.cos(ang))*(K@K)

Fp = lambda r: math.pi/(1.0+r)          # hedgehog profile, correct B=1 tail exponent s=1 (R-130)

rng = np.random.default_rng(7)
worst_lock = 0.0
for _ in range(60):
    ax = rng.normal(size=3); ang = rng.uniform(0, 2*math.pi)
    Rsp = so3(ax, ang); A = su2(ax, ang)
    for _ in range(6):
        x = rng.normal(size=3)*1.7
        lhs = A @ Umat(Rsp.T @ x, Fp) @ A.conj().T
        worst_lock = max(worst_lock, np.abs(lhs - Umat(x, Fp)).max())
check("B1 grand-spin lock  A U(R^-1 x) A^dag = U(x) for the DIAGONAL (R,A) pair",
      worst_lock < 1e-12, f"max dev {worst_lock:.2e}")

# a NON-diagonal pair must fail (the stabilizer is exactly the diagonal, not bigger)
bad = 0.0
for _ in range(30):
    ax1 = rng.normal(size=3); ax2 = rng.normal(size=3); ang = rng.uniform(0.4, 2.5)
    Rsp = so3(ax1, ang); A = su2(ax2, ang)
    if np.abs(np.array(ax1)/np.linalg.norm(ax1) - np.array(ax2)/np.linalg.norm(ax2)).max() < 1e-3:
        continue
    x = rng.normal(size=3)*1.3
    bad = max(bad, np.abs(A @ Umat(Rsp.T @ x, Fp) @ A.conj().T - Umat(x, Fp)).max())
check("B2 a MIS-matched (R,A) pair does NOT stabilize (stabilizer is exactly SU(2)_diag)",
      bad > 1e-3, f"max dev {bad:.2e}")

dimG = 3 + 3 + 3          # translations + spatial rotations + isorotations
dim_stab_B1 = 3           # SU(2)_diag
dim_M1 = dimG - dim_stab_B1
check("B3 dim M_1(exact) = 9 - 3 = 6 = 3 positions + 3 internal SU(2)", dim_M1 == 6, f"= {dim_M1}")

print()
print("="*78)
print("C.  THE COUNTING OBSTRUCTION:  dim M_N(exact) <= 9 for EVERY N, vs 6N needed")
print("="*78)

# B=2 axial torus: the rational map z^2 carries a U(1) stabilizer (engine-verified in R-136:
# R(e^{i a} z) = e^{2 i a} R  <=>  spatial rot_3(a) undone by iso_3(2a) ).
import sympy as sp
z, al = sp.symbols('z alpha')
check("C1 R-136 axial relation  (e^{i a} z)^2 = e^{2ia} z^2  (=> U(1) stabilizer of the B=2 torus)",
      sp.simplify((sp.exp(sp.I*al)*z)**2 - sp.exp(2*sp.I*al)*z**2) == 0)

rows = []
for N in range(1, 7):
    dim_stab = {1: 3, 2: 1}.get(N, 0)      # B=1 SU(2)_diag; B=2 axial U(1); B>=3 generically discrete
    dim_exact = dimG - dim_stab
    need = 6*N                              # 3 positions + 3 internal per defect (tensor-product target)
    pos_exact = 3                           # ONLY the centre of mass is an exact zero mode for N>=2
    rows.append((N, dim_exact, need, pos_exact, 3*N))
print(f"  {'N':>2} {'dim M_N(exact)<=':>18} {'6N (needed)':>12} {'exact positions':>16} {'3N (needed)':>12}")
for N, de, need, pe, pn in rows:
    print(f"  {N:>2} {de:>18} {need:>12} {pe:>16} {pn:>12}")
check("C2 exact moduli dimension is N-INDEPENDENT and bounded by dim(E(3) x SU(2)_iso) = 9",
      all(de <= 9 for _, de, _, _, _ in rows))
check("C3 deficit: 6N - dim M_N(exact) > 0 for all N >= 2",
      all(need > de for N, de, need, _, _ in rows if N >= 2))
check("C4 exact positions = 3 (CoM) for all N; missing relative positions = 3(N-1)",
      all(pe == 3 for _, _, _, pe, _ in rows))
check("C5 for N >= 2 even the raw dimension 3N of POSITIONS alone exceeds the 3 available",
      all(pn > 3 for N, _, _, _, pn in rows if N >= 2))

print()
print("="*78)
print("D.  WHY the relative positions are NOT moduli: the engine's own BPS deficit + binding")
print("="*78)
r135 = twt.multi_skyrmion_b2_classical_binding()
E1 = float(r135['b1_regression']['mass_coeff'])
E2 = float(r135['b2']['mass_coeff'])
thr = float(r135['inequality']['threshold_coeff'])
margin = float(r135['inequality']['margin'])
faddeev = 12*math.pi**2
# engine's own normalisation check: per_baryon_12pi2 reported for B=2
pb2_engine = float(r135['b2']['per_baryon_12pi2'])
ratio2 = 4*E2/(2*faddeev)
ratio1 = 4*E1/(1*faddeev)
check("D1 normalisation reproduces the engine's own per_baryon_12pi2 for B=2",
      abs(ratio2 - pb2_engine) < 1e-9, f"{ratio2:.6f} vs {pb2_engine:.6f}")
print(f"  E(B=1)/12pi^2 = {ratio1:.4f}      E(B=2)/(2*12pi^2) = {ratio2:.4f}")
print(f"  binding margin (1 - E2/2E1)     = {margin:.6f}  ({100*margin:.3f} %)")
check("D2 BPS/Faddeev bound is NOT saturated: E/(12 pi^2 B) > 1 at both B",
      ratio1 > 1.2 and ratio2 > 1.2, f"deficit B=1 {100*(ratio1-1):.1f}%, B=2 {100*(ratio2-1):.1f}%")
check("D3 binding is STRICTLY positive => the separation direction has a non-zero potential",
      E2 < thr and margin > 0)
print("  => the relative-separation coordinate costs energy (it connects E2 to the threshold),")
print("     so it is a MASSIVE mode, not a zero mode. No index theorem delivers 6N here.")

print()
print("="*78)
print("E.  THE PER-DEFECT QUBIT: L^2(SU(2)) with the Z2 (spinorial) character")
print("="*78)
# Peter-Weyl:  L^2(SU(2)) = sum_J  V_J (x) V_J^* ,  dim (2J+1)^2.
# The Z2 sector f(-A) = -f(A) keeps exactly the HALF-INTEGER J.  Lowest = J=1/2, dim 4.
def haar_sample(n, rng):
    q = rng.normal(size=(n,4)); q /= np.linalg.norm(q, axis=1, keepdims=True)
    A = np.empty((n,2,2), dtype=complex)
    A[:,0,0] = q[:,0] + 1j*q[:,3]; A[:,0,1] = q[:,2] + 1j*q[:,1]
    A[:,1,0] = -q[:,2] + 1j*q[:,1]; A[:,1,1] = q[:,0] - 1j*q[:,3]
    return A
rng2 = np.random.default_rng(11)
A = haar_sample(400000, rng2)
# J=1/2 matrix elements are the entries of A themselves -> 4 functions
f = np.stack([A[:,0,0], A[:,0,1], A[:,1,0], A[:,1,1]], axis=1)
G = (f.conj().T @ f)/f.shape[0]
check("E1 the four J=1/2 matrix elements are Haar-orthogonal with norm^2 = 1/(2J+1) = 1/2",
      np.abs(G - 0.5*np.eye(4)).max() < 5e-3, f"max dev {np.abs(G-0.5*np.eye(4)).max():.2e}")
check("E2 they are SPINORIAL: f(-A) = -f(A) (odd under the centre) => selected by the Z2 character",
      True, "(linear in A, exact)")
check("E3 dim of the lowest spinorial band = (2J+1)^2 = 4 = spin-doublet (x) isospin-doublet",
      4 == 2*2)

print()
print("="*78)
print("F.  R-136's COLLECTIVE B=2 SPECTRUM vs the ANTISYMMETRISED TENSOR PRODUCT")
print("="*78)
# two B=1 defects, each in the (I,J) = (1/2,1/2) band  -> internal space C^4 (x) C^4 = 16
# antisymmetric part has dim 4*3/2 = 6 ; symmetric part 4*5/2 = 10
dim1 = 4
dim_anti = dim1*(dim1-1)//2
dim_sym = dim1*(dim1+1)//2
check("F1 antisym(C^4 (x) C^4) = 6 ; sym = 10 ; total 16", (dim_anti, dim_sym) == (6, 10))
# SU(2)_I x SU(2)_J decomposition of (1/2,1/2)^{(x)2}
decomp = {(I,J): (2*I+1)*(2*J+1) for I in (0,1) for J in (0,1)}
anti_set = {(0,1),(1,0)}                 # antisymmetric under simultaneous label exchange
sym_set  = {(0,0),(1,1)}
check("F2 sum of dims over the ANTISYM (I,J) set == 6",
      sum(decomp[k] for k in anti_set) == dim_anti, str({k: decomp[k] for k in anti_set}))
check("F3 sum of dims over the SYM (I,J) set == 10",
      sum(decomp[k] for k in sym_set) == dim_sym, str({k: decomp[k] for k in sym_set}))
# R-136's FR selection rule on the collective (ONE-FIELD, no tensor product) B=2 moduli space
fr_allowed = {(I,J) for I in (0,1) for J in (0,1) if (-1)**(I+J) == -1}
bose_allowed = {(I,J) for I in (0,1) for J in (0,1) if (-1)**(I+J) == +1}
check("F4 R-136 fermionic rule (I+J odd) selects EXACTLY the antisymmetrised set",
      fr_allowed == anti_set, str(sorted(fr_allowed)))
check("F5 R-136 bosonic branch (I+J even) selects EXACTLY the symmetrised set",
      bose_allowed == sym_set, str(sorted(bose_allowed)))
# ... and the same is true in the engine's own table
import inspect
r136_ok = True
try:
    _ = twt.b2_axial_quantization_deuteron_ground_state()
    print("  (R-136 primitive ran; its own asserts passed)")
except Exception as ex:
    r136_ok = False
    print("  R-136 raised:", ex)
check("F6 R-136 primitive executes with its internal asserts intact", r136_ok)
# HONEST BOUND on the match: the collective tower is BIGGER than the 16
extra = [(I,J) for I in range(3) for J in range(4) if (-1)**(I+J) == -1 and not (I<=1 and J<=1)]
print(f"  scope: the match is on the I,J <= 1 sector only. The collective tower also allows"
      f"\n         {extra} which have NO image in the 16-dim two-nucleon internal space.")

print()
print("="*78)
print("G.  DOES THE MODULI METRIC FACTORISE?  two-defect product ansatz, cross block")
print("="*78)
# U(x) = U_1(x - R1) U_2(x - R2), hedgehogs.  g_{R1^i, R2^j} = Int Re Tr[ dU/dR1^i ^dag  dU/dR2^j ]
def hedge_field(X, Y, Z, F):
    r = np.sqrt(X**2 + Y**2 + Z**2) + 1e-12
    Fv = np.pi/(1.0 + r)
    c = np.cos(Fv); s = np.sin(Fv)
    nx, ny, nz = X/r, Y/r, Z/r
    U = np.empty(X.shape + (2,2), dtype=complex)
    U[...,0,0] = c + 1j*s*nz
    U[...,0,1] = 1j*s*(nx - 1j*ny)
    U[...,1,0] = 1j*s*(nx + 1j*ny)
    U[...,1,1] = c - 1j*s*nz
    return U

def matmul(Aa, Bb):
    return np.einsum('...ij,...jk->...ik', Aa, Bb)
def dag(Aa):
    return np.conj(np.swapaxes(Aa, -1, -2))

L, n = 12.0, 96
ax = np.linspace(-L, L, n); dv = (ax[1]-ax[0])**3
X, Y, Z = np.meshgrid(ax, ax, ax, indexing='ij')

def cross_block(d, comp=0):
    """g_{R1^comp , R2^comp} for separation d along z."""
    h = 0.02
    def U_of(R1, R2):
        U1 = hedge_field(X-R1[0], Y-R1[1], Z-R1[2], None)
        U2 = hedge_field(X-R2[0], Y-R2[1], Z-R2[2], None)
        return matmul(U1, U2)
    ehat = np.zeros(3); ehat[comp] = 1.0
    R1 = np.array([0,0,-d/2.0]); R2 = np.array([0,0,+d/2.0])
    d1 = (U_of(R1+h*ehat, R2) - U_of(R1-h*ehat, R2))/(2*h)
    d2 = (U_of(R1, R2+h*ehat) - U_of(R1, R2-h*ehat))/(2*h)
    g12 = np.real(np.einsum('...ij,...ij->...', np.conj(d1), d2)).sum()*dv
    g11 = np.real(np.einsum('...ij,...ij->...', np.conj(d1), d1)).sum()*dv
    g22 = np.real(np.einsum('...ij,...ij->...', np.conj(d2), d2)).sum()*dv
    return g11, g22, g12

print("   d      g_11        g_22        g_12(cross)   |g12|/sqrt(g11 g22)")
prev = None
decays = True
vals = []
for d in (1.0, 2.0, 3.0, 4.0, 6.0):
    g11, g22, g12 = cross_block(d, comp=2)
    frac = abs(g12)/math.sqrt(abs(g11*g22))
    vals.append(frac)
    print(f"  {d:4.1f}  {g11:10.4f}  {g22:10.4f}  {g12:12.5f}   {frac:.4f}")
check("G1 the cross block g_{R1,R2} is NON-ZERO at finite separation",
      max(vals) > 1e-3, f"max fraction {max(vals):.4f}")
check("G2 it DECAYS with separation (=> factorisation is an ASYMPTOTIC statement only)",
      vals[-1] < vals[0], f"{vals[0]:.4f} -> {vals[-1]:.4f}")

print()
print("="*78)
print("H.  THE Z2 MENU/PICK BOOKKEEPING (canon 2: menu vs pick)")
print("="*78)
# pi_1 of the N-soliton configuration space = Z2 (IMPORT: pi_4(S^3)=Z2 + Finkelstein-Rubinstein).
# Given that, the quantisation menu is Hom(Z2, U(1)) = Hom(Z2, {+-1}).
chars = [chi for chi in ([lambda g: 1, lambda g: (-1)**g])]
vals_h = [tuple(chi(g) for g in (0,1)) for chi in chars]
check("H1 Hom(Z2, U(1)) has EXACTLY 2 elements -> a 2-item menu, so the pick is 1 INPUT bit",
      len(set(vals_h)) == 2, str(vals_h))
print("  H2 [IMPORT, not engine-checkable]: in pi_1 = Z2 the 2pi-ROTATION loop and the")
print("     two-defect EXCHANGE loop are the SAME generator (Finkelstein-Rubinstein 1968).")
print("     CONSEQUENCE (engine-trivial, but the load-bearing one): a single character cannot")
print("     assign different signs to one generator => SPIN-STATISTICS IS FORCED once the")
print("     import is granted; only the BRANCH is free, and it is the SAME single bit already")
print("     on the books as the W-LIVE-4 fork (N32b / N35 / R-141).")

print()
print("="*78)
n_pass = sum(1 for _, ok in OK if ok)
print(f"SUMMARY: {n_pass}/{len(OK)} checks passed")
for name, ok in OK:
    if not ok:
        print("  FAILED:", name)
