# -*- coding: utf-8 -*-
"""PROBE: the C^1 vs C^2 contradiction in V3 SSB.4  (read-only; nothing banked)
Run from knowledge/corpus with PYTHONUTF8=1.
"""
import math, cmath, random, itertools
import numpy as np
import twt
from twt import MV, e

ONE = MV.from_dict({(): 1.0})
ZERO = MV.from_dict({})
e4 = e(4)
I4 = e(1, 2, 3, 4)

EVEN_NAMES = ["1", "e12", "e13", "e14", "e23", "e24", "e34", "I4"]
EVEN = {"1": ONE, "e12": e(1,2), "e13": e(1,3), "e14": e(1,4),
        "e23": e(2,3), "e24": e(2,4), "e34": e(3,4), "I4": I4}
KEYS8 = [(), (1,2), (1,3), (1,4), (2,3), (2,4), (3,4), (1,2,3,4)]

def co(x):  # coordinate vector on the 8 even blades
    return np.array([x.coeff(k) for k in KEYS8], float)

def comm(a, b): return a*b - b*a
def nz(x): return float(np.linalg.norm(co(x)))

print("="*78)
print("(a)  DIMENSION COUNTS IN THE ENGINE")
print("="*78)

r020 = twt.born_subspace_one_B_forced()
print("R-020 born_subspace_one_B_forced -> intersections per winding choice:")
for k, v in r020["intersections_per_winding_choice"].items():
    print("     B_a = %-4s : (W)&(S)&(E) = %s   real dim = %d" % (k, v, len(v)))

# (W)&(E) alone: even blades commuting with e4
W = [n for n in EVEN_NAMES if comm(e4, EVEN[n]) == ZERO]
notW = [n for n in EVEN_NAMES if n not in W]
print("\n(W)&(E)  = even blades commuting with e4 : %s   real dim = %d" % (W, len(W)))
print("excluded by (W)                           : %s   real dim = %d" % (notW, len(notW)))

B = e(1,2)   # the defect-selected winding blade / phase blade
S = [n for n in EVEN_NAMES if comm(B, EVEN[n]) == ZERO]
print("(S)&(E)  = even blades commuting with B_a=e12 : %s" % S)

print("\nREAL vs COMPLEX dimension of each candidate:")
print("   phase sector span{1,B_a}          real dim 2   -> complex dim 1  (C^1)")
print("   commutant Z_{Cl+}(e4)=span{1,e12,e13,e23}  real dim 4 -> complex dim 2  (C^2)")

# verify Z(e4) is closed under multiplication and is a quaternion algebra
Zb = [ONE, e(1,2), e(1,3), e(2,3)]
Zn = ["1", "e12", "e13", "e23"]
closed = all(any(nz(Zb[i]*Zb[j] - s*Zb[k]) < 1e-12 for k in range(4) for s in (1.0,-1.0))
             for i in range(4) for j in range(4))
print("\nZ_{Cl+}(e4) closed under multiplication : %s" % closed)
i_, j_, k_ = e(1,2), e(1,3), e(2,3)
print("  i^2=%s  j^2=%s  k^2=%s" % (i_*i_, j_*j_, k_*k_))
print("  e12*e13 = %s      e13*e12 = %s   (anticommute: %s)"
      % (i_*j_, j_*i_, comm(i_, j_) != ZERO))
print("  => Z_{Cl+}(e4) is isomorphic to the quaternions H (real dim 4).")

print()
print("="*78)
print("(b)  THE PER-DEFECT INTERNAL SPACES THE SUBSTRATE OFFERS")
print("="*78)

# --- charge decomposition of the 8 even blades under U(1) generated by B_a=e12 ---
print("\n[b4] CHARGE DECOMPOSITION under Ad(exp(theta*e12/2)) :")
def adjoint(X, th):
    R = twt.exp_unit_bivector(B, th/2.0)
    return R * X * R.reverse()
for n in EVEN_NAMES:
    X = EVEN[n]
    # numerically extract the U(1) weight: track over a full turn
    th = 0.37
    Y = adjoint(X, th)
    same = nz(Y - X) < 1e-12
    if same:
        q = 0
    else:
        # weight q means it mixes with a partner at frequency q*theta
        # find q by fitting the coefficient of X in Ad(X) = cos(q*theta)
        c = float(co(Y) @ co(X) / (co(X) @ co(X)))
        q = round(math.acos(max(-1.0, min(1.0, c)))/th)
    print("   %-4s : adjoint U(1)_{B_a} charge |q| = %d" % (n, q))
print("   charge-0 sector  : {1, e12, e34, I4}      (4 real)")
print("   charged sector   : {e13, e14, e23, e24}   (4 real, two |q|=1 doublets)")

print("\n[b3] FR-ODD COLLECTIVE ROTATIONAL BAND of L^2(SU(2)) :")
for jj in [0.0, 0.5, 1.0, 1.5]:
    print("   j = %-3s  dim (2j+1)^2 = %d   %s" %
          (jj, int(round((2*jj+1)**2)),
           "FR-odd (fermionic) : ALLOWED" if abs(jj*2 - round(jj*2)) < 1e-9 and int(round(2*jj)) % 2 == 1
           else "FR-even : forbidden for a fermionic B=1 Skyrmion"))
print("   lowest FR-odd level j=1/2 -> dim 4 = C^2_spin (x) C^2_isospin")

print()
print("="*78)
print("(c)  CAN THE PHASE SECTOR (C^1) HOST THE BELL WING?  --- NO.")
print("="*78)

# The SSB.4 states, literally as written: psi_0 = 1, psi_a = R_a psi_0, R_a = exp(theta_a B/2)
def psi_line(theta):
    return twt.exp_unit_bivector(B, theta/2.0) * ONE

def z_overlap_line(p, q):
    """the C-native Hermitian inner product on span{1,B}, EXACTLY as
    born_exponent_gleason_closure defines it: grade-0 part AND B part."""
    pr = p.reverse() * q
    return complex(pr.coeff(()), pr.coeff((1,2)))

print("\nSSB.4 as written: psi_0 = 1, psi_a = exp(theta_a*B/2)*psi_0  in span{1,B} = C^1")
print("%-10s %-10s | %-22s %-10s | %-12s" %
      ("theta_a", "theta_b", "Hermitian <psi_a|psi_b>", "|.|", "grade-0 only"))
for (ta, tb) in [(0.0, 0.0), (0.0, math.pi/4), (0.0, math.pi/2), (0.0, math.pi),
                 (0.3, 1.9), (0.0, 2*math.pi)]:
    pa, pb = psi_line(ta), psi_line(tb)
    z = z_overlap_line(pa, pb)
    g0 = (pa.reverse()*pb).coeff(())
    print("%-10.4f %-10.4f | %-22s %-10.6f | %-12.6f   [cos(dth/2)=%.6f]" %
          (ta, tb, "%+.4f%+.4fi" % (z.real, z.imag), abs(z), g0, math.cos((tb-ta)/2)))

print("""
READ THIS OFF:  in C^1 the Hermitian overlap has modulus 1 for EVERY pair of angles.
Born probability |<psi_a|psi_b>|^2 = 1 identically.  All the states R_a psi_0 are the
SAME RAY: the projective space of C^1 is a single point (CP^0).  The number cos(dth/2)
that SSB.4 quotes is the GRADE-0 PART ONLY, i.e. Re of that overlap -- which is the
inner product of the REAL 2-plane span{1,B}, not of the complex line.""")

# and the engine ITSELF flags grade-0-only as an undercount:
print("The engine already flags exactly this truncation. born_exponent_gleason_closure")
print("asserts (SSB.3.3 undercount): grade-0-only misses the phase-rotated ray entirely.")
Dref, psi_rot = ONE, B
print("   <1~ * B>_0            = %.6f   (grade-0 only  -> 'orthogonal')" % (Dref.reverse()*psi_rot).coeff(()))
print("   |z_overlap(1, B)|     = %.6f   (true Hermitian -> SAME RAY)"
      % abs(z_overlap_line(Dref, psi_rot)))

print()
print("="*78)
print("(c2) THE COMMUTANT Z(e4) = H IS A QUBIT.  EXPLICIT CONSTRUCTION.")
print("="*78)

# right-multiplication by B is the complex structure J on the 4-real-dim Z(e4)
def Jr(x): return x * B
for n, X in zip(Zn, Zb):
    print("   J(%-4s) = %-14s   J^2(%-4s) = %s" % (n, Jr(X), n, Jr(Jr(X))))
print("   => J^2 = -1 on Z(e4): right-mult by B_a makes H a COMPLEX vector space.")

# C-basis: {1, e13}.  Check span_C{1, e13} = Z(e4)
print("\n   C-basis {1, e13}:   1*B = %s ;  e13*B = %s" % (ONE*B, e(1,3)*B))
print("   so  span_R{1, 1*B, e13, e13*B} = span_R{1, e12, e13, e23} = Z(e4).  dim_C = 2.")

def to_C2(x):
    """coordinates of x in Z(e4) w.r.t. the C-basis {1, e13}, C-structure = RIGHT mult by B."""
    a0, a1 = x.coeff(()), x.coeff((1,2))       # 1 and 1*B = e12
    b0 = x.coeff((1,3))                        # e13
    b1 = x.coeff((2,3))                         # e13*B = e13*e12 = +e23
    return np.array([complex(a0, a1), complex(b0, b1)])

def from_C2(z):
    return (z[0].real*ONE + z[0].imag*e(1,2) + z[1].real*e(1,3) + z[1].imag*e(2,3))

# round-trip check
rnd = random.Random(7)
worst = 0.0
for _ in range(200):
    x = sum((rnd.gauss(0,1)*Zb[t] for t in range(1,4)), rnd.gauss(0,1)*ONE)
    worst = max(worst, nz(from_C2(to_C2(x)) - x))
print("   round-trip Z(e4) <-> C^2 max error over 200 draws : %.3e" % worst)

# LEFT multiplication by Z(e4) units is C-LINEAR (commutes with right mult by B)
worst = 0.0
for _ in range(200):
    g = sum((rnd.gauss(0,1)*Zb[t] for t in range(1,4)), rnd.gauss(0,1)*ONE)
    x = sum((rnd.gauss(0,1)*Zb[t] for t in range(1,4)), rnd.gauss(0,1)*ONE)
    worst = max(worst, nz((g*x)*B - g*(x*B)))
print("   [left-mult, right-mult] max error over 200 draws  : %.3e  (associativity => C-linear)" % worst)

# the one-sided rotor action of the L-orbit Spin(3) is SU(2) on C^2
print("\n   L-orbit rotors acting on the LEFT are SU(2) on C^2 (matrix in basis {1,e13}):")
for nm, blade, th in [("exp(t*e12/2)", e(1,2), 0.8), ("exp(t*e13/2)", e(1,3), 0.8),
                      ("exp(t*e23/2)", e(2,3), 0.8)]:
    R = twt.exp_unit_bivector(blade, th/2.0)
    M = np.stack([to_C2(R*from_C2(np.array([1+0j,0j]))),
                  to_C2(R*from_C2(np.array([0j,1+0j])))], axis=1)
    uni = np.linalg.norm(M.conj().T@M - np.eye(2))
    print("      %-14s theta=%.1f  det=%+.4f%+.4fi  ||U^dag U - 1||=%.1e" %
          (nm, th, np.linalg.det(M).real, np.linalg.det(M).imag, uni))
    print("         M = [[%+.4f%+.4fi, %+.4f%+.4fi], [%+.4f%+.4fi, %+.4f%+.4fi]]" %
          (M[0,0].real, M[0,0].imag, M[0,1].real, M[0,1].imag,
           M[1,0].real, M[1,0].imag, M[1,1].real, M[1,1].imag))

print("""
   NOTE the split of roles, visible in those three matrices:
     - the rotor in the PHASE plane B_a=e12 is DIAGONAL: it acts as a phase, it moves
       no ray in the e12-charge-0 direction -- this is why SSB.4's own choice of
       measurement plane (B) cannot generate a Bell wing.
     - the rotors in the DISCARDED commutant planes e13, e23 are genuinely OFF-DIAGONAL:
       they move the ray.  These are the Bell measurement rotations.""")

print()
print("="*78)
print("(c3) THE SSB.4 NUMBER cos(dtheta/2) IS RECOVERED EXACTLY -- IN C^2, HERMITIAN,")
print("     WITH NO GRADE-0 TRUNCATION -- ONCE THE ROTATION PLANE IS e13 (or e23).")
print("="*78)

def herm(x, y):
    zx, zy = to_C2(x), to_C2(y)
    return complex(np.vdot(zx, zy))

print("\npsi_0 = 1 ;  psi_a = exp(theta_a * e13 / 2) * psi_0   (rotation OUT of the phase plane)")
print("%-9s %-9s | %-24s %-10s | %-12s %-12s" %
      ("th_a", "th_b", "Hermitian <psi_a|psi_b>", "|.|", "|.|^2", "cos^2(dth/2)"))
mx = 0.0
for (ta, tb) in [(0.0,0.0), (0.0,math.pi/4), (0.0,math.pi/2), (0.0,math.pi),
                 (0.0,2*math.pi), (0.31,1.87), (-1.1,2.4)]:
    pa = twt.exp_unit_bivector(e(1,3), ta/2.0)*ONE
    pb = twt.exp_unit_bivector(e(1,3), tb/2.0)*ONE
    z = herm(pa, pb)
    mx = max(mx, abs(abs(z) - abs(math.cos((tb-ta)/2))))
    print("%-9.4f %-9.4f | %-24s %-10.6f | %-12.6f %-12.6f" %
          (ta, tb, "%+.6f%+.6fi" % (z.real, z.imag), abs(z), abs(z)**2,
           math.cos((tb-ta)/2)**2))
print("max |  |<a|b>| - |cos(dth/2)|  | = %.3e" % mx)

# random check over 400 settings
mx = 0.0
for _ in range(400):
    ta, tb = rnd.uniform(-7,7), rnd.uniform(-7,7)
    pa = twt.exp_unit_bivector(e(1,3), ta/2.0)*ONE
    pb = twt.exp_unit_bivector(e(1,3), tb/2.0)*ONE
    mx = max(mx, abs(abs(herm(pa,pb)) - abs(math.cos((tb-ta)/2))))
print("400 random settings: max deviation from |cos(dth/2)| = %.3e" % mx)
print("   => the half-angle SSB.4 calls 'the one genuinely geometric ingredient'")
print("      SURVIVES the repair; it is the C^2 Hermitian overlap, not a truncation.")

print()
print("="*78)
print("(c4) THE DISCARDED UNITS {e13,e23} CARRY THE SINGLET PAIRING (N53's clue) -- CHECK")
print("="*78)

def eps(u, v, jj):
    """N53's pairing: eps(u,v) = <j u, v>  with j one of the discarded commutant units."""
    return complex(np.vdot(to_C2(jj*u), to_C2(v)))

for jname, jb in [("e13", e(1,3)), ("e23", e(2,3)), ("e12 (the PHASE blade)", e(1,2))]:
    anti = sym = 0.0
    clin = 0.0
    inv = 0.0
    for _ in range(200):
        u = from_C2(np.array([complex(rnd.gauss(0,1),rnd.gauss(0,1)),
                              complex(rnd.gauss(0,1),rnd.gauss(0,1))]))
        v = from_C2(np.array([complex(rnd.gauss(0,1),rnd.gauss(0,1)),
                              complex(rnd.gauss(0,1),rnd.gauss(0,1))]))
        anti = max(anti, abs(eps(u,v,jb) + eps(v,u,jb)))
        sym  = max(sym,  abs(eps(u,v,jb) - eps(v,u,jb)))
        # C-linearity in the 2nd slot vs antilinearity
        clin = max(clin, abs(eps(u, v*B, jb) - 1j*eps(u,v,jb)))
        # SU(2) invariance under LEFT L-orbit rotors
        cs = [rnd.gauss(0,1) for _ in range(3)]
        nn = math.sqrt(sum(c*c for c in cs)); cs = [c/nn for c in cs]
        ax = cs[0]*e(1,2)+cs[1]*e(1,3)+cs[2]*e(2,3)
        R = twt.exp_unit_bivector(ax, rnd.uniform(-3,3))
        inv = max(inv, abs(eps(R*u, R*v, jb) - eps(u,v,jb)))
    print("  j = %-22s : max|eps(u,v)+eps(v,u)| = %.2e   max|eps(u,v)-eps(v,u)| = %.2e"
          % (jname, anti, sym))
    print("      %-22s   C-bilinear (2nd slot) dev = %.2e   SU(2)-invariance dev = %.2e"
          % ("", clin, inv))

# is eps the standard symplectic form?
u = from_C2(np.array([1+0j, 0j])); v = from_C2(np.array([0j, 1+0j]))
for jname, jb in [("e13", e(1,3)), ("e23", e(2,3))]:
    print("  j=%-4s :  eps(|0>,|1>) = %s   eps(|1>,|0>) = %s   eps(|0>,|0>) = %s"
          % (jname, eps(u,v,jb), eps(v,u,jb), eps(u,u,jb)))

print()
print("="*78)
print("(c5) WHAT USING Z(e4) COSTS -- does it destroy R-020's UNIQUENESS?")
print("="*78)

# The uniqueness claim is about OPERATORS. Recompute the commutant of the LEFT action
# restricted to Z(e4), and the algebra of operators preserving the background.
print("""
R-020 forces {1,B_a} as the set of even-grade rotor elements X with [X,e4]=[X,B_a]=0.
That is a statement about OPERATORS.  Test whether it survives when the fluctuation
MODULE is enlarged from span{1,B_a} to Z(e4).""")

# operators = left multiplications by elements of Cl+(4,0); which ones are C-linear
# for the right-B complex structure AND preserve the background direction B_a?
print("\n  (i) which left-multiplications are C-LINEAR on Z(e4)?  ALL of them:")
print("      left and right multiplication commute by associativity (checked above, 4e-15).")
print("  (ii) which left-multiplications by even blades map Z(e4) into Z(e4)?")
for n in EVEN_NAMES:
    X = EVEN[n]
    stays = all(nz((X*Y) - sum(( (X*Y).coeff(KEYS8[t])*EVEN[EVEN_NAMES[t]] for t in [0,1,2,4]), ZERO)) < 1e-12
                for Y in Zb)
    print("      %-4s : maps Z(e4)->Z(e4) : %s" % (n, stays))

print("""
  (iii) the SCHUR statement, which is what uniqueness really is.  The left action of
        Z(e4)=H on itself is irreducible over the right-C structure, and its COMMUTANT
        inside End_C(Z(e4)) is exactly the right multiplications by span{1,B_a} = C.""")
# verify: operators commuting with all left multiplications = right multiplications
# and the ones that additionally preserve the C-structure are right-mult by {1,B}
import numpy.linalg as la
basisR = []
for Y in Zb:
    M = np.zeros((4,4))
    for c, X in enumerate(Zb):
        M[:, c] = np.array([ (X*Y).coeff(k) for k in [(), (1,2), (1,3), (2,3)] ])
    basisR.append(M)
# commutant of the left regular rep
Ls = []
for Y in Zb:
    M = np.zeros((4,4))
    for c, X in enumerate(Zb):
        M[:, c] = np.array([ (Y*X).coeff(k) for k in [(), (1,2), (1,3), (2,3)] ])
    Ls.append(M)
rows = []
for L in Ls:
    K = np.kron(np.eye(4), L) - np.kron(L.T, np.eye(4))
    rows.append(K)
from scipy.linalg import null_space
NS = null_space(np.vstack(rows), rcond=1e-10)
print("      dim of the commutant of the LEFT regular rep (real)      = %d  (= right mult by H)" % NS.shape[1])
# now intersect with C-linearity (commute with right-mult by B)
RB = basisR[1]
rows2 = rows + [np.kron(np.eye(4), RB) - np.kron(RB.T, np.eye(4))]
NS2 = null_space(np.vstack(rows2), rcond=1e-10)
print("      ... intersected with C-linearity (commuting with right-B) = %d  (= C = span{1,B_a})" % NS2.shape[1])

print("""
  READ-OFF:  the C-linear commutant of the spin action on Z(e4) is exactly 2-real-dimensional
  = span{1, B_a} = C.  So R-020's forced 2-dim object is EXACTLY the Schur commutant of the
  qubit, and enlarging the MODULE to C^2 does not touch it.  The uniqueness that SSB.3.1's
  argument rests on is a statement about the complex STRUCTURE (the operator algebra), and it
  survives verbatim.  What does NOT survive is the additional, separately-flagged ANSATZ that
  the fluctuation itself lies in that 2-dim commutant.""")

print("\n  (iv) THE PRICE, stated exactly: imposing (S) on the STATE (not just the operator)")
print("       freezes the qubit.  Explicit: the sub-line span{1,B_a} is invariant under the")
print("       e12-rotor and its ray is FIXED:")
for th in [0.0, 1.0, 2.0, 3.0]:
    R = twt.exp_unit_bivector(B, th/2.0)
    z = to_C2(R*ONE)
    print("       exp(%.1f*e12/2)*1 -> C^2 coords (%+.4f%+.4fi, %+.4f%+.4fi)  |z2|=%.1e"
          % (th, z[0].real, z[0].imag, z[1].real, z[1].imag, abs(z[1])))
print("       the second C-coordinate is identically 0: (S)-respecting rotations never")
print("       leave the ray.  A Bell wing needs a rotation that violates (S).")

print()
print("="*78)
print("(c6) COHERENCE CHECK AGAINST R-127 (the mass phase rides B_a)")
print("="*78)
print("""
R-127 locks the observer-visible mass phase to the winding blade B_a.  In the C^2 picture
that is exactly 'the mass phase is the global C-SCALAR': right multiplication by
exp(omega*tau5*B_a/2).  Verify that this phase is C-scalar (acts as e^{i.} on BOTH
C-coordinates) and therefore commutes with the SU(2) spin action -- i.e. the repair does
not disturb R-127.""")
om, t5 = 0.937, 1.7
P = twt.exp_unit_bivector(B, om*t5/2.0)
mx = 0.0
for _ in range(200):
    x = from_C2(np.array([complex(rnd.gauss(0,1),rnd.gauss(0,1)),
                          complex(rnd.gauss(0,1),rnd.gauss(0,1))]))
    z0, z1 = to_C2(x), to_C2(x*P)
    mx = max(mx, np.max(np.abs(z1 - cmath.exp(1j*om*t5/2.0)*z0)))
print("   max ||to_C2(x*exp(w t5 B/2)) - e^{i w t5/2} to_C2(x)|| over 200 draws = %.3e" % mx)
mx = 0.0
for _ in range(200):
    cs = [rnd.gauss(0,1) for _ in range(3)]
    nn = math.sqrt(sum(c*c for c in cs)); cs=[c/nn for c in cs]
    ax = cs[0]*e(1,2)+cs[1]*e(1,3)+cs[2]*e(2,3)
    R = twt.exp_unit_bivector(ax, rnd.uniform(-3,3))
    x = from_C2(np.array([complex(rnd.gauss(0,1),rnd.gauss(0,1)),
                          complex(rnd.gauss(0,1),rnd.gauss(0,1))]))
    mx = max(mx, nz((R*x)*P - R*(x*P)))
print("   max ||[spin rotor, mass phase]|| over 200 draws                        = %.3e" % mx)
print("   => phase (right, C) and spin (left, SU(2)) act on the SAME 4-real-dim space")
print("      without conflict.  This is the textbook H = C^2 picture, and it is the")
print("      substrate's OWN commutant, not an import.")

print()
print("="*78)
print("(c7) DOES A REAL 2-PLANE (a 'rebit') SUFFICE FOR CHSH=2sqrt2? -- the fallback")
print("="*78)
print("""
If one insists on keeping the fluctuation in span{1,B_a} and reading the grade-0 part as
the inner product, one is doing REAL quantum mechanics on R^2 (a rebit).  Two rebits do
reach 2sqrt2 at coplanar settings, so CHSH alone does not discriminate.  What DOES
discriminate, and what the corpus already owns:
  - the C-structure i := B_a would then be USED UP as a state direction, contradicting
    SSB.3.1/R-020/R-127, which all need B_a to be the PHASE;
  - born_exponent_gleason_closure's Hermitian overlap (grade-0 + B part) is then not the
    inner product of the Bell section -- two incompatible inner products in one paper.""")
# demonstrate the two inner products are genuinely different functionals
mx = 0.0
for _ in range(200):
    a = rnd.gauss(0,1)*ONE + rnd.gauss(0,1)*B
    b = rnd.gauss(0,1)*ONE + rnd.gauss(0,1)*B
    g0 = (a.reverse()*b).coeff(())
    zz = abs(z_overlap_line(a,b))
    mx = max(mx, abs(abs(g0) - zz))
print("max | |grade-0 overlap| - |Hermitian overlap| | over 200 random {1,B} pairs = %.4f" % mx)
print("   (nonzero: they are DIFFERENT functionals, not two names for one thing.)")
print()
print("DONE.")
