# READ-ONLY PROBE — review item II-4: what are the six set-aside blades of SB.3.1?
# Run:  cd knowledge/corpus && PYTHONUTF8=1 python ../candidates/probes_2026-07-29/six_blades_probe.py
import sys, os, itertools
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "corpus"))
import twt
from twt import MV, e, I4, SCALAR

def nm(b):
    return "1" if not b else "e" + "".join(map(str, b))

EVEN = [(), (1,2), (1,3), (1,4), (2,3), (2,4), (3,4), (1,2,3,4)]
BL = {b: MV.from_dict({b: 1.0}) for b in EVEN}
B  = e(1,2)                      # B_a = e12, the SB.3.1 defect-selected winding axis

def comm(x, y): return x*y - y*x
def eq(x, y, tol=1e-12):
    d = (x - y).as_dict()
    return all(abs(v) < tol for v in d.values())

print("="*78)
print("STEP 1 — ad(B) charge decomposition of the 8 even blades of Cl+(4,0), B = e12")
print("="*78)
neutral, charged = [], []
for b in EVEN:
    c = comm(B, BL[b])
    if eq(c, MV.from_dict({})):
        neutral.append(b)
    else:
        charged.append(b)
    print(f"  [B, {nm(b):>6}] = {c!r}")
print(f"\n  CHARGE-0 (commutant): {[nm(b) for b in neutral]}")
print(f"  CHARGED            : {[nm(b) for b in charged]}")
assert [nm(b) for b in neutral] == ["1", "e12", "e34", "e1234"]
assert [nm(b) for b in charged] == ["e13", "e14", "e23", "e24"]

# charge weights via finite rotor conjugation
print("\n  -- weights under R(t)=exp(t*B/2), X -> R X ~R (period in t) --")
import math
for b in charged:
    t = 0.37
    R = MV.from_dict({(): math.cos(t/2), (1,2): math.sin(t/2)})
    Xr = R * BL[b] * R.reverse()
    d = Xr.as_dict()
    partner = [k for k in d if k != b]
    print(f"   {nm(b):>5} -> cos(t)*{nm(b)} + sin(t)*{nm(partner[0])}   "
          f"(cos={d[b]:+.6f} vs {math.cos(t):+.6f}; sin={d[partner[0]]:+.6f})")

print()
print("="*78)
print("STEP 2 — RIGHT-multiplication by B (the generator SB.3.1's ansatz actually uses:")
print("         'the modes generated by right-multiplication by the defect-selected B')")
print("="*78)
lines, seen = [], set()
for b in EVEN:
    if b in seen: continue
    img = BL[b] * B
    (pb, pc), = img.terms
    lines.append((b, pb, pc)); seen.add(b); seen.add(pb)
    print(f"   {nm(b):>6} * B = {pc:+.0f}*{nm(pb):<6}   -> complex line span{{{nm(b)}, {nm(pb)}}}")
print("\n  => Cl+(4,0) = FOUR complex lines under right-B (a C^4):")
for b, pb, pc in lines:
    print(f"       {{{nm(b)}, {nm(pb)}}}")
print("     KEPT by SB.3.1 : {1, e12}")
print("     SET ASIDE      : {e34, e1234}  (neutral)  +  {e13,e23}, {e14,e24}  (charged)")
assert len(lines) == 4

print()
print("="*78)
print("STEP 3 — the two NEUTRAL set-aside blades are exactly I4 * (the kept line)")
print("="*78)
print(f"   I4 * 1   = {I4*SCALAR!r}")
print(f"   I4 * e12 = {I4*B!r}")
assert eq(I4*SCALAR, BL[(1,2,3,4)])
assert eq(I4*B, -1.0*BL[(3,4)])
print("   => span{e34, I4} = I4 . span{1, B}   EXACT.")
print("   I4 is central in Cl+(4,0) with I4^2 = +1:")
for b in EVEN:
    assert eq(comm(I4, BL[b]), MV.from_dict({})), b
print(f"     [I4, X] = 0 for all 8 even blades: True;  I4^2 = {I4*I4!r}")
Pp = 0.5*(SCALAR + I4); Pm = 0.5*(SCALAR - I4)
print(f"     chiral projectors P_+ = {Pp!r}, P_- = {Pm!r}; P_+^2 = P_+ : {eq(Pp*Pp, Pp)}")
print("   => the kept line {1,B} and the neutral set-aside line {e34,I4} are the SAME")
print("      complex line seen in the two I4-chirality halves H_+ = P_+ Cl+, H_- = P_- Cl+:")
print(f"        P_+ * 1   = {Pp*SCALAR!r}")
print(f"        P_- * 1   = {Pm*SCALAR!r}")
print("      Keeping only {1,B} imposes psi_+ = psi_-  (chirality-diagonal), i.e. it DROPS")
print("      the chiral partner - it does not drop a new/extra field.")

print()
print("="*78)
print("STEP 4 — which of the 8 are actually DYNAMICAL directions of the substrate field?")
print("         (SD.3.2: the substrate field is a UNIT rotor R; SD.4.6 linearizes R = R_vac(1+dR))")
print("="*78)
# reverse-constraint: R~R = 1  =>  dR + reverse(dR) = 0 at linear order
for b in EVEN:
    X = BL[b]
    s = X + X.reverse()
    print(f"   {nm(b):>6}: X + ~X = {s!r:>18}   -> {'KILLED by |R|=1 (not a rotor direction)' if not eq(s, MV.from_dict({})) else 'allowed (grade-2 / rotor-tangent)'}")
print("\n   => rotor-tangent space = grade 2 ONLY (6-dim). Grade-0 (1) and grade-4 (I4)")
print("      are NOT fluctuation directions of a unit-rotor field.")
print("      Of the SIX set aside: I4 is non-dynamical; e13,e14,e23,e24,e34 are the")
print("      five genuine grade-2 channels.  NOTE: the KEPT sector's 'f' direction (the")
print("      scalar 1) is non-dynamical by the SAME identity - cf. SSB.6.3(i) 'the rotor-norm")
print("      direction, frozen by |R| = 1 (non-propagating, SD.3.2)'.")

print()
print("="*78)
print("STEP 5 — the FREE (Face-1) quadratic form on the six grade-2 channels")
print("         L_kin = (1/2) <Omega_mu Omega^mu>_0 ,  Omega_mu = ~R d_mu R ,  dR = sum_a phi_a B_a")
print("="*78)
BIV = [(1,2),(1,3),(1,4),(2,3),(2,4),(3,4)]
print("   metric  G_ab = <B_a B_b>_0 :")
hdr = "        " + "".join(f"{nm(b):>8}" for b in BIV); print(hdr)
G = []
for a in BIV:
    row = []
    for b in BIV:
        row.append((BL[a]*BL[b]).coeff(()))
    G.append(row)
    print(f"   {nm(a):>5} " + "".join(f"{v:>8.1f}" for v in row))
assert all(G[i][j] == (-1.0 if i == j else 0.0) for i in range(6) for j in range(6))
print("\n   => G_ab = -delta_ab EXACTLY: the quadratic kinetic form is blade-DIAGONAL and")
print("      DEGENERATE across all six grade-2 channels ('six grade-2 channels sharing one")
print("      stiffness', R-163). No channel is distinguished; no channel carries a mass term.")

print()
print("="*78)
print("STEP 6 — can the Omega-built action gap ANY of the six? (R-041 shift symmetry, checked)")
print("="*78)
import random
random.seed(7)
def rand_rotor():
    c = {(): random.uniform(-1,1)}
    for b in BIV: c[b] = random.uniform(-1,1)
    X = MV.from_dict(c)
    n = math.sqrt((X*X.reverse()).coeff(()))
    return MV.from_dict({b: v/n for b, v in X.as_dict().items()})
g0 = rand_rotor(); R = rand_rotor(); dR = rand_rotor()   # dR stands in for d_mu R
Om   = R.reverse() * dR
Om_g = (g0*R).reverse() * (g0*dR)
print(f"   Omega(R)      = {Om!r}")
print(f"   Omega(g0 R)   = {Om_g!r}")
print(f"   identical? {eq(Om, Om_g)}")
print("   => every Omega-built term (kinetic AND Skyrme) is invariant under the CONSTANT")
print("      left shift R -> g0 R. A constant rotor configuration therefore costs ZERO action,")
print("      so NO non-derivative phi^2 (mass) term can appear in the Omega-built sector.")
print("      ALL SIX grade-2 directions are EXACTLY FLAT there. (This is R-041 verbatim:")
print("      'a non-linearly realized Goldstone shift on the six grade-2 fluctuation")
print("      directions - they are flat / Goldstone directions'.)")
print("      The ONLY term in L_medium that is not Omega-built is L_top(D) (SD.4.4), whose")
print("      coefficient mu is stated OPEN / gated on the substrate dynamics.")

print()
print("="*78)
print("STEP 7 — the banked gap COUNT on the realistic (canted) vacuum, and WHICH channels")
print("="*78)
ng = twt.n_goldstone_canted_FM()
print(f"   n_goldstone_canted_FM() -> {ng}")
print("   induced_G_from_linear_face_band(): canted vacuum = 'N_G = 2 (2 gapless + 4 gapped)")
print("     - exact 6-band Bogoliubov structure UN-BANKED'")
print()
print("   The broken group is SU(2)_L = the L-ORBIT rotor target span{e12,e13,e23}")
print("   (SD.3.2: R_i in Spin(3)). Check it closes as an su(2):")
for a, b in itertools.combinations([(1,2),(1,3),(2,3)], 2):
    print(f"     [{nm(a)}, {nm(b)}] = {comm(BL[a], BL[b])!r}")
print("   Q-bivectors {e14,e24,e34} are NOT in SU(2)_L -> they can never be coset/Goldstone")
print("   directions of the canted FM ground state. Check they leave the L-orbit:")
for a in [(1,2),(1,3),(2,3)]:
    for b in [(1,4),(2,4),(3,4)]:
        c = comm(BL[a], BL[b])
        if c.terms:
            print(f"     [{nm(a)}, {nm(b)}] = {c!r}")
print()
print("   ALIGNMENT THEOREM (the part that does NOT depend on the un-banked 6-band structure):")
print("     gapless 2-plane C = SU(2)_L/U(1)_canting  lies inside span{e12,e13,e23} (dim 3),")
print("     dim C = 2; the SB.3.1 KEPT sector contains exactly ONE grade-2 direction (B=e12).")
print("     dim(C n span{B}) <= 1  =>  dim(C \\ kept) >= 1.")
print("     ==> AT LEAST ONE of the six set-aside blades is an EXACTLY GAPLESS physical mode,")
print("         for EVERY orientation of the canting axis. Generically (canting axis not")
print("         orthogonal to B inside SU(2)_L) BOTH gapless modes are among the six.")
print("     Special case canting axis || B_a: C = span{e13, e23} = exactly the CHARGED")
print("         L-doublet -> both gapless modes are set-aside, and they are charged +/-1.")
print("     Special case canting axis _|_ B_a in SU(2)_L (say axis = e13):")
print("         C = span{e12, e23} -> one gapless mode is the KEPT B, one is set aside (e23).")

print()
print("="*78)
print("STEP 8 — cross-check against the sector labels the corpus already assigns to grade 2")
print("="*78)
print(f"   twt.L_BIVECTORS = {sorted(twt.L_BIVECTORS)}   (SB.5: MAGNETIC part of the strain F)")
print(f"   twt.Q_BIVECTORS = {sorted(twt.Q_BIVECTORS)}   (SB.5: ELECTRIC part of the strain F)")
print("   The six set-aside blades contain:")
print("     ALL THREE Q-bivectors e14, e24, e34  (the entire ELECTRIC sector), and")
print("     TWO of the three L-bivectors e13, e23 (two of three MAGNETIC components),")
print("     plus the non-dynamical I4.")
print("   The KEPT sector {1, B=e12} retains ONE magnetic component and NO electric component.")
